<?php

declare(strict_types=1);

namespace App\Notifications\AdminPanel;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;

/**
 * In-app (database) alert for the admin notification feed — BACKEND_SPEC §5.11.
 * Generated by platform events via the AdminPanel observers. `entity` carries a
 * deep-link key (e.g. ['unit_id' => 5]) that NotificationsController maps to the
 * spec's { type, id }. Database channel only — the admin feed is in-app.
 */
class AdminAlert extends Notification
{
    use Queueable;

    /** @param array<string, mixed> $entity */
    public function __construct(
        public readonly string $category,
        public readonly string $title,
        public readonly string $message,
        public readonly array $entity = [],
    ) {
    }

    /** @return array<int, string> */
    public function via(object $notifiable): array
    {
        return ['database'];
    }

    /** @return array<string, mixed> */
    public function toArray(object $notifiable): array
    {
        return array_merge([
            'category' => $this->category,
            'title'    => $this->title,
            'message'  => $this->message,
        ], $this->entity);
    }
}
